notifications:
  email: false
language: go
go:
  - "1.6.2"
  - "1.5.4"
env:
  - ETCDV=2.3.7
  - ETCDV=2.2.5
  - ETCDV=2.1.3
  - ETCDV=2.0.13
install:
  - "wget https://github.com/coreos/etcd/releases/download/v${ETCDV}/etcd-v${ETCDV}-linux-amd64.tar.gz"
  - "tar -zxvf etcd-v${ETCDV}-linux-amd64.tar.gz"
  - "etcd-v${ETCDV}-linux-amd64/etcd -name travis &"
  - "sleep 5" # Wait for etcd to come up
cache: apt
script: "make get && make test"
